on: 
    push:
        branches:
            - main
            
name: Deploy WPForms Quiz Score Plugin
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: test/wp-content/plugins/wp-form-oprions-score/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env*
            **/tests/**
            README.md
            .gitignore
            .env